---
- hosts: all
  become: true
  gather_facts: yes
  vars:
  user_name: serge2024
  group_name: devops
  tasks:
    - name: Check the time
      command: date
      when: ansible_distribution == "serge" or ansible_processor_nproc == 2
    - name: create user serge
      user:
         name: "{{user_name}}"
         comment: Serge Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: Install package
      package:
        name: vim
        state: present  
 
